import * as React from "react";
import { Box, Button, IconButton, TextField, useTheme } from "@mui/material";
import Dialog from "@mui/material/Dialog";
import { tokens } from "../../themes";
import DialogTitle from "@mui/material/DialogTitle";
import CustomText from "../CustomText/CustomText";
import { Close, CopyAll, CopyAllOutlined } from "@mui/icons-material";
import { QRCodeCanvas } from "qrcode.react";
import copy from "copy-to-clipboard";  

export default function OTPModal({ open, handleClose }) {
  const theme = useTheme();
  const colors = tokens(theme.palette.mode);
  const [otp, setOtp] = React.useState();
  const onChangeotp = (event) => {
    setOtp(event.target.value);
  };
  const [copyText, setCopyText] = React.useState('KNSDKONASNKN65644MM');
  const CopyToClipboard = () => {
     copy(copyText);
  }
  return (
    <div>
      <Dialog
        open={open}
        onClose={handleClose}
        aria-labelledby="alert-dialog-title"
        aria-describedby="alert-dialog-description"
        PaperProps={{
          style: {
            minWidth: "700px",
            backgroundColor:
              theme.palette.mode === "dark" ? "#28094A" : "white",
            borderRadius: "20px",
            paddingBottom: "25px",
          },
        }}
      >
        <div
          style={{
            display: "flex",
            justifyContent: "space-between",
            flexDirection: "row",
            paddingRight: "20px",
          }}
        >
          <DialogTitle
            id="alert-dialog-title"
            fontSize={25}
            color={theme.palette.mode === "light" ? "#28094A" : "white"}
          >
            {"Enable OTP"}
          </DialogTitle>
          <IconButton style={{ marginTop: "10px" }} onClick={handleClose}>
            <Close
              sx={{
                color: theme.palette.mode === "light" ? "#28094A" : "white",
              }}
            />
          </IconButton>
        </div>
        <Box width={"80%"} flexDirection="column" display={"flex"} ml="3%">
          <CustomText
            ml="0px"
            text={`Install Google Authenticator on your smartphone. (Apple, Android).`}
          />
          <CustomText
            ml="0px"
            text={`Open Google Authenticator, click “Add an account” / “Scan QR code”.`}
          />
          <CustomText
            ml="0px"
            text={`Scan the QR code below (and optionally backup the generated secret).`}
          />
          <CustomText
            ml="0px"
            text={`Enter the generated one-time password into this form.`}
          />
        </Box>
        <Box
          sx={{
            display: "flex",
            flexDirection: "row",
            marginTop: "3%",
            width: "90%",
            justifySelf: "center",
            justifyContent: "space-between",
          }}
        >
          <Box width={"50%"} sx={{ display: "flex", ml: "10%" }}>
            <QRCodeCanvas
              value="https://reactjs.org/"
              style={{
                backgroundColor: "white",
                padding: "5px",
              }}
            />
          </Box>
          <Box width="50%" display={"flex"} flexDirection="column">
            <CustomText
              ml="0px"
              text={`OTP secret (we recommend you to backup this secret
safely to prevent authentication issues in case you lost your device)`}
            />
            <Box
            mt='8%'
            display={'flex'}
            justifyContent='space-between'
            alignItems={'center'}
            sx={{
              paddingY:'3%',
              borderBottom:'1px solid white'
            }}
            >
              <CustomText ml="0px" text={"KNSDKONASNKN65644MM"} />
             <IconButton
             onClick={CopyToClipboard}
             >
              <CopyAllOutlined />
              </IconButton>
            </Box>
            <CustomText
              ml="0px"
              mt="10%"
              text={`Enter the one-time password
generated by your OTP app.`}
            />
            <TextField
              id="outlined-basic"
              variant="outlined"
              type={"text"}
              sx={{
                width: "80%",
                marginTop: "2%",
                backgroundColor:
                  theme.palette.mode === "dark" ? "#4A3067" : "white",
              }}
              placeholder={"xxx xxx xxx"}
              value={otp}
              onChange={onChangeotp}
            />
          </Box>
        </Box>
        <Box
          sx={{
            display: "flex",
            justifyContent: "center",
            marginTop: "6%",
          }}
        >
          <Button
            sx={{
              width: "140px",
              ml: "10px",
              color: theme.palette.mode === "dark" ? "white" : "#361956",
              marginTop: "20px",
              borderRadius: "20px",
              alignSelf: "center",
              borderColor: "white !important",
            }}
            variant="outlined"
            onClick={handleClose}
          >
            Cancel
          </Button>
          <Button
            sx={{
              width: "25%",
              ml: "10px",
              marginTop: "20px",
              background: "#F85844",
              borderRadius: "20px",
              alignSelf: "center",
            }}
            variant="contained"
            onClick={handleClose}
          >
            Enable OTP
          </Button>
        </Box>
      </Dialog>
    </div>
  );
}
